Mappings: 
  RegionMap: 
    us-east-1: 
      "HVM64": "ami-0a313d6098716f372"
    us-east-2: 
      "HVM64": "ami-0c55b159cbfafe1f0"
    us-west-1: 
      "HVM64": "ami-06397100adf427136"
    us-west-2: 
      "HVM64": "ami-005bdb005fb00e791"
    ap-south-1: 
      "HVM64": "ami-007d5db58754fa284"
    ap-southeast-1: 
      "HVM64": "ami-0dad20bd1b9c8c004"
    ap-southeast-2: 
      "HVM64": "ami-0b76c3b150c6b1423"
    ap-northeast-1: 
      "HVM64": "ami-0eb48a19a8d81e20b"
    ca-central-1: 
      "HVM64": "ami-01b60a3259250381b"
    eu-west-1: 
      "HVM64": "ami-08d658f84a6d84a80"
Parameters:
  key:
    Description : Name of an existing EC2 key pair for SSH access to the EC2 instance
    Type: AWS::EC2::KeyPair::KeyName
    Default: sikandar-Key-pair-Ohio

Resources:
  PublicLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties: 
      Subnets:
        - !ImportValue sikandarStack-Subnet1
        - !ImportValue sikandarStack-Subnet3
      Scheme: internet-facing  
      SecurityGroups: 
        - !ImportValue sikandarStack-PublicSecurityGroup
      Listeners:
        - LoadBalancerPort: 80
          InstancePort: 80
          Protocol: HTTP
        - LoadBalancerPort: 22
          InstancePort: 22
          Protocol: TCP 
      HealthCheck:  
        Target: HTTP:80/
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'
      Tags:
        - Key: Name
          Value: sikandarStack




  PrivateLoadBalancer:
    Type: AWS::ElasticLoadBalancing::LoadBalancer
    Properties:
      Subnets:
        - !ImportValue sikandarStack-Subnet2  
      Scheme: internal  
      SecurityGroups: 
        - !ImportValue sikandarStack-PrivateSecurityGroup
      Listeners:
        - LoadBalancerPort: 3306
          InstancePort: 3306
          Protocol: TCP
        - LoadBalancerPort: 22
          InstancePort: 22
          Protocol: TCP 
      HealthCheck:
        Target: HTTP:80/
        HealthyThreshold: '3'
        UnhealthyThreshold: '5'
        Interval: '30'
        Timeout: '5'
      Tags:
        - Key: Name
          Value: AWS::StackName          


  LaunchConfigurationPublic: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", HVM64]
      InstanceType: t2.micro
      UserData:
        Fn::Base64: !Sub 
          - |
            #!/bin/bash
            set -x
            sleep 2m
            apt-get -y update
            apt-get install apache2 -y
            apt-get install mysql-server -y
            apt-get install php-mysql -y
            apt-get install php libapache2-mod-php -y
            apt-get install zip -y
            cd /var/www
            rm -rf html
            wget https://s3.amazonaws.com/alamkey/html1.zip
            unzip html1.zip
            sed -i -e 's/localhost/${PrivateIP}/g' /var/www/html/config.php
          - PrivateIP:
              !ImportValue PrivateInsIp            
      KeyName:
        Ref: key
      SecurityGroups: 
        - !ImportValue sikandarStack-PublicSecurityGroupIns


  LaunchConfigurationPrivate: 
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      InstanceId: !ImportValue sikandarStack-privateIns







  AutoScalingGroup1: 
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AvailabilityZones:
        - !ImportValue sikandarStack-AvailabilityZone1
        - !ImportValue sikandarStack-AvailabilityZone3
      LaunchConfigurationName: !Ref LaunchConfigurationPublic
      MinSize: 2
      MaxSize: 4
      VPCZoneIdentifier: 
        - !ImportValue  sikandarStack-Subnet1
        - !ImportValue  sikandarStack-Subnet3      
      LoadBalancerNames: 
        - Ref: PublicLoadBalancer

  AutoScalingGroup2: 
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AvailabilityZones:
        - !ImportValue sikandarStack-AvailabilityZone2
      LaunchConfigurationName: !Ref LaunchConfigurationPrivate
      MinSize: 1
      MaxSize: 1
      VPCZoneIdentifier: 
        - !ImportValue  sikandarStack-Subnet2     
      LoadBalancerNames: 
        - Ref: PrivateLoadBalancer
